import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 1. ENGINEERING DECK (The Tech Docs)
  // Scans the 'docs/tech' folder
  tech: [
    {
      type: 'autogenerated',
      dirName: 'tech', 
    },
  ],

  // 2. CAPTAIN'S LOG (The Blog/Updates)
  // Scans the 'docs/log' folder
  log: [
    {
      type: 'autogenerated',
      dirName: 'log',
    },
  ],

  // 3. ARCHIVE (Old WSL content)
  // Scans the 'docs/archive' folder
  archive: [
    {
      type: 'autogenerated',
      dirName: 'archive',
    },
  ],
};

export default sidebars;