import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  // ── AIVERSE MAIN (intro, updates, support, map) ──
  aiverse: [
    { type: 'doc', id: 'aiverse/aiverse-index',   label: '📖 What is AIverse?' },
    { type: 'doc', id: 'aiverse/updates/aiverse-updates', label: "🗒️ Author's Updates" },
    { type: 'link', label: '🗺️ Cosmic Map', href: '/cosmos' },
    { type: 'doc', id: 'aiverse/aiverse-support', label: '⚔️ Support the Chronicle' },
  ],

  // ── ERA I — flat post list, no collapsible ──
  era_i: [
    {
      type: 'html',
      value: '<div class="sidebar-era-header"><span class="sidebar-era-header-icon">⚡</span>Era I — The Bigbang<span class="sidebar-era-header-range">M1–M10</span></div>',
      defaultStyle: true,
    },
    { type: 'doc', id: 'aiverse/era-i-bigbang/the-cogitator-stirs', label: 'I · The Cogitator Stirs' },
    { type: 'doc', id: 'aiverse/era-i-bigbang/the-first-synapse',   label: 'II · The First Synapse' },
    { type: 'doc', id: 'aiverse/era-i-bigbang/the-glass-window',    label: 'III · The Glass Window' },
    { type: 'doc', id: 'aiverse/era-i-bigbang/the-long-march',      label: 'IV · The Long March' },
  ],

  // ── ERA II — The Awakening ──
  era_ii: [
    {
      type: 'html',
      value: '<div class="sidebar-era-header"><span class="sidebar-era-header-icon">🌅</span>Era II — The Awakening<span class="sidebar-era-header-range">M11–M25</span></div>',
      defaultStyle: true,
    },
    { type: 'doc', id: 'aiverse/era-ii-awakening/aiverse-era-ii-awakening', label: 'Era II Overview' },
    { type: 'doc', id: 'aiverse/era-ii-awakening/the-proving-grounds', label: 'I. The Proving Grounds' },
    { type: 'doc', id: 'aiverse/era-ii-awakening/the-steel-bones', label: 'II. The Steel Bones' },
    { type: 'doc', id: 'aiverse/era-ii-awakening/the-growing-eye', label: 'III. The Growing Eye' },
    { type: 'doc', id: 'aiverse/era-ii-awakening/the-weight-of-a-name', label: 'IV. The Weight of a Name' },
  ],

  // ── ERA III ──
  era_iii: [
    {
      type: 'html',
      value: '<div class="sidebar-era-header"><span class="sidebar-era-header-icon">👁️</span>Era III — The Omnissiah Stirs<span class="sidebar-era-header-range">M26–M45</span></div>',
      defaultStyle: true,
    },
    { type: 'doc', id: 'aiverse/era-iii-omnissiah/aiverse-era-iii-omnissiah', label: 'Chronicles Incoming' },
  ],

  // ── ERA IV ──
  era_iv: [
    {
      type: 'html',
      value: '<div class="sidebar-era-header"><span class="sidebar-era-header-icon">🌀</span>Era IV — The Warp Opens<span class="sidebar-era-header-range">M46–M55</span></div>',
      defaultStyle: true,
    },
    { type: 'doc', id: 'aiverse/era-iv-warp/aiverse-era-iv-warp', label: 'Chronicles Incoming' },
  ],

  // ── ERA V ──
  era_v: [
    {
      type: 'html',
      value: '<div class="sidebar-era-header"><span class="sidebar-era-header-icon">🔥</span>Era V — The Reborn<span class="sidebar-era-header-range">M56–M62</span></div>',
      defaultStyle: true,
    },
    { type: 'doc', id: 'aiverse/era-v-reborn/aiverse-era-v-reborn', label: 'Chronicles Incoming' },
  ],

  // ── ERA VI ──
  era_vi: [
    {
      type: 'html',
      value: '<div class="sidebar-era-header"><span class="sidebar-era-header-icon">∞</span>Era VI — The Living Chronicle<span class="sidebar-era-header-range">M63+</span></div>',
      defaultStyle: true,
    },
    { type: 'doc', id: 'aiverse/era-vi-chronicle/aiverse-era-vi-chronicle', label: 'Chronicles Incoming' },
  ],

  // ── OLD TOPICS (preserved content) ──
  tech: [{ type: 'autogenerated', dirName: 'tech' }],
  log:  [{ type: 'autogenerated', dirName: 'log' }],
  archive: [{ type: 'autogenerated', dirName: 'archive' }],
};

export default sidebars;
